name: reusemart_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  intl: ^0.19.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
